### ISSUE TITLE
Whitebox resetting working directory to whitebox directory in Anaconda environment

### ISSUE THREAD

**Issue by arojas314** [giswqs/whitebox-python#30]
* whitebox version: 2.0.3
* Python version: 3.9
* Operating System: RedHat Enterprise

### Description
When using any whitebox functions for python, the current working directory is reset to the whitebox directory in my anaconda environment (e.g. /home/user_name/minconda3/envs/osgeo-env-v1/lib/python3.8/site-packages/whitebox). This causes many problems, since I am using whitebox functions across multiple scripts for my automated workflow.

To clarify, after importing whitebox, the current working directory is set to my project directory where my python file is calling whitebox, which is what I want. But after using a function it is reset to the whitebox directory, so the functions do not end up running.

I am attempting this in jupyter notebook. 

### What I Did

```
from whitebox import whitebox_tools
wbt = whitebox_tools.WhiteboxTools()
CWD = "/home/user_name/project/data"
wbt.set_working_dir(CWD)
wbt.clip_lidar_to_polygon("./filename.las", polygons="./poly_shapefile.shp", output="./lidarClip.las")

```

Below is the error messages I receive.

![image](https://user-images.githubusercontent.com/57734585/136865407-37fece79-f7be-4b91-bdc1-925ea072978f.png)

Thank you for your time in reading this.

**Comment by giswqs** [comment]
I just tested it, and everything seems to work fine. Your `CWD` and `--wd` in the output are different directories. They are supposed to be the same. Not sure why they are different on your computer.  

![image](https://user-images.githubusercontent.com/5016453/136867558-ce3f9347-1102-446d-9ccd-55c75978bbc7.png)

**Comment by giswqs** [comment]
You can either provide absolute paths to input files or use `wbt.set_working_dir("/absolute/path/to/wd")`, and then you can use relative paths

I noticed that every time a tool is executed, the working directory is changed to the wbt exe path. Therefore, you can no longer use `os.getcwd()` to set the working directory. This is the behavior of [whitebox_tools.py](https://www.whiteboxgeo.com/manual/wbt_book/python_scripting/using_whitebox_tools.html). It needs to be fixed by @jblindsay. `os.chdir(self.exe_path)` is used 10 times in the script. One potential solution is to reset the working directory at the end of a wbt function.
https://github.com/jblindsay/whitebox-tools/blob/master/whitebox_tools.py#L171

```
cwd = os.getcwd()
os.chdir(self.exe_path)

# at the end
os.chdir(cwd)
```
